### ISSUE TITLE
IMPROVEMENT: Making User Class Abstract.

### ISSUE THREAD

**Issue by SharathRajMohan** [SharathRajMohan/JustGo#7]
Since user objects can't exist in their proper form, We can make this class abstract.

Reporter: @Harsh436  
Assigned to: @Revathireddy97

**Comment by Revathireddy1997** [comment]
Fixed in commit:  https://github.com/SharathRajMohan/JustGo/commit/f008823bd4fd0a77544f896a919db5fd37554237
